# Generated by Django 5.0 on 2023-12-25 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_phone",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=128)),
                ("position", models.CharField(max_length=128)),
                ("subjects", models.CharField(max_length=128)),
                (
                    "image",
                    models.ImageField(default="default.png", upload_to="profile/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
